# Generated by Django 4.2.25 on 2025-10-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_pendingpage_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiconfiguration',
            name='test_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wikiconfiguration',
            name='test_revision_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
