# Generated by Django 4.2.25 on 2025-10-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_editorprofile_is_former_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrevision',
            name='render_error_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingrevision',
            name='rendered_html',
            field=models.TextField(blank=True),
        ),
    ]
