# Generated by Django 4.2.25 on 2025-10-09 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0004_editorprofile_is_former_bot"),
        ("reviews", "0004_wikiconfiguration_test_mode_and_more"),
    ]

    operations = []
