# Generated by Django 4.2.25 on 2025-10-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_wikiconfiguration_redirect_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiconfiguration',
            name='revertrisk_threshold',
            field=models.FloatField(default=0.0, help_text='Threshold for revertrisk score (0.0-1.0). Edits with a score above this threshold will not be auto-approved. Set to 0.0 to disable revertrisk checking.'),
        ),
    ]
