# Generated by Django 4.2.25 on 2025-10-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_pendingpage_wikidata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='test_mode',
            field=models.BooleanField(default=False, help_text='If enabled, use test revision IDs instead of real flagged pages'),
        ),
        migrations.AddField(
            model_name='wiki',
            name='test_revision_ids',
            field=models.CharField(blank=True, help_text='Comma-separated revision IDs for test mode (e.g. 12345, 67890)', max_length=255),
        ),
    ]
