# Generated by Django 4.2.25 on 2025-10-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_pendingpage_wikidata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorprofile',
            name='is_former_global_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='editorprofile',
            name='is_global_bot',
            field=models.BooleanField(default=False),
        ),
    ]
