# Generated by Django for PendingChangesBot-ng

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0008_add_superseded_similarity_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikiconfiguration",
            name="ml_model_type",
            field=models.CharField(
                max_length=50,
                default='revertrisk',
                choices=[
                    ('revertrisk', 'Revert Risk (language-agnostic)'),
                    ('damaging', 'Damaging Edit Detection'),
                    ('goodfaith', 'Good Faith Prediction'),
                    ('articlequality', 'Article Quality Assessment'),
                    ('articletopic', 'Article Topic Classification'),
                ],
                help_text="Which Wikimedia ML model to use for this wiki"
            ),
        ),
        migrations.AddField(
            model_name="wikiconfiguration",
            name="ml_model_threshold",
            field=models.FloatField(
                default=0.0,
                help_text="Threshold for ML model score (0.0-1.0). Edits with a score above this threshold will not be auto-approved. Set to 0.0 to disable ML model checking.",
            ),
        ),
        migrations.AlterField(
            model_name="wikiconfiguration",
            name="revertrisk_threshold",
            field=models.FloatField(
                default=0.0,
                help_text="DEPRECATED: Use ml_model_threshold instead. Threshold for revertrisk score (0.0-1.0). Edits with a score above this threshold will not be auto-approved. Set to 0.0 to disable revertrisk checking.",
            ),
        ),
    ]
