# Generated by Django 4.2.25 on 2025-10-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0010_modelscores"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikiconfiguration",
            name="revertrisk_threshold",
            field=models.FloatField(
                blank=True,
                help_text="Revert risk threshold (0.0-1.0). Set to None to disable check.",
                null=True,
            ),
        ),
    ]
