# Generated by Django 4.2.25 on 2025-10-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_editorprofile_is_former_global_bot_and_more'),
        ('reviews', '0017_merge_20251027_1806'),
    ]

    operations = [
    ]
