# Generated by Django 4.2.25 on 2025-10-29 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_merge_20251027_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_id', models.BigIntegerField(db_index=True)),
                ('stable_word_id', models.CharField(db_index=True, max_length=100)),
                ('word', models.CharField(max_length=500)),
                ('author_user_name', models.CharField(blank=True, max_length=255)),
                ('author_user_id', models.BigIntegerField(blank=True, null=True)),
                ('previous_word_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('position', models.IntegerField()),
                ('is_moved', models.BooleanField(default=False)),
                ('is_modified', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('exists_in_latest', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_annotations', to='reviews.pendingpage')),
            ],
            options={
                'ordering': ['revision_id', 'position'],
                'indexes': [models.Index(fields=['page', 'revision_id'], name='reviews_wor_page_id_dd569b_idx'), models.Index(fields=['stable_word_id'], name='reviews_wor_stable__66ef89_idx'), models.Index(fields=['author_user_name'], name='reviews_wor_author__b67613_idx')],
                'unique_together': {('page', 'revision_id', 'stable_word_id', 'position')},
            },
        ),
        migrations.CreateModel(
            name='RevisionAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_id', models.BigIntegerField()),
                ('start_revision_id', models.BigIntegerField(blank=True, null=True)),
                ('end_revision_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('words_annotated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_annotations', to='reviews.pendingpage')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('page', 'revision_id')},
            },
        ),
    ]
