# Generated by Django 4.2.25 on 2025-11-01 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0018_add_test_mode_fields"),
        ("reviews", "0018_alter_reviewactivity_unique_together_and_more"),
    ]

    operations = []
