# Generated by Django 4.2.25 on 2025-11-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_alter_reviewactivity_unique_together_and_more'),
        ('reviews', '0018_merge_20251030_1226'),
    ]

    operations = [
    ]
