name: Auto Format

on:
  pull_request:
    types: [ labeled ]
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  format:
    name: Auto-format code with Ruff
    runs-on: ubuntu-latest
    if: github.event.label.name == 'auto-format'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install Ruff
      run: pip install ruff

    - name: Run Ruff formatting
      run: ruff format app/

    - name: Check for changes
      id: verify_diff
      run: git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

    - name: Commit and push if changed
      if: steps.verify_diff.outputs.changed == 'true'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "style: auto-format code with Ruff [skip ci]"
        git push
