name: Security

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # Type checking with mypy
#  type-check:
#    name: Type Check (mypy)
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: '3.9'
#          cache: 'pip'
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
#
#      - name: Run mypy type checking
#        run: |
#          cd app && python -m mypy reviews --config-file=../pyproject.toml

  # Security scanning with Ruff (Bandit rules)
  security-scan:
    name: Security Scan (Ruff/Bandit)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Ruff security checks
        run: |
          python -m ruff check --select S app/

  # Dependency vulnerability scanning with pip-audit
  dependency-scan:
    name: Dependency Scan (pip-audit)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install pip-audit
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit

      - name: Run pip-audit on requirements.txt
        run: |
          python -m pip_audit -r requirements.txt --desc --ignore-vuln GHSA-wv4w-6qv2-qqfg
